[2024-08-28T02:58:23.297+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-28T02:58:23.314+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movies_dag.leer_data scheduled__2024-06-26T00:00:00+00:00 [queued]>
[2024-08-28T02:58:23.321+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movies_dag.leer_data scheduled__2024-06-26T00:00:00+00:00 [queued]>
[2024-08-28T02:58:23.322+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 4
[2024-08-28T02:58:23.332+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): leer_data> on 2024-06-26 00:00:00+00:00
[2024-08-28T02:58:23.344+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=70) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-28T02:58:23.345+0000] {standard_task_runner.py:72} INFO - Started process 72 to run task
[2024-08-28T02:58:23.345+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'movies_dag', 'leer_data', 'scheduled__2024-06-26T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpjgq9g1jt']
[2024-08-28T02:58:23.347+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask leer_data
[2024-08-28T02:58:23.390+0000] {task_command.py:467} INFO - Running <TaskInstance: movies_dag.leer_data scheduled__2024-06-26T00:00:00+00:00 [running]> on host 988f997ce349
[2024-08-28T02:58:23.619+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='pedro' AIRFLOW_CTX_DAG_ID='movies_dag' AIRFLOW_CTX_TASK_ID='leer_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-26T00:00:00+00:00'
[2024-08-28T02:58:23.620+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-28T02:58:23.648+0000] {bd_connect.py:25} INFO - Connecting to database...
[2024-08-28T02:58:23.649+0000] {dag_intermediario.py:32} ERROR - ('Connection could not be made due to the following error: \n', ValueError("invalid literal for int() with base 10: 'None'"))
[2024-08-28T02:58:23.649+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-08-28T02:58:23.658+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-28T02:58:23.659+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=movies_dag, task_id=leer_data, run_id=scheduled__2024-06-26T00:00:00+00:00, execution_date=20240626T000000, start_date=20240828T025823, end_date=20240828T025823
[2024-08-28T02:58:23.681+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-28T02:58:23.696+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-28T02:58:23.698+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
