[2024-08-28T03:03:08.433+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-28T03:03:08.708+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movies_dag.leer_data manual__2024-08-28T03:03:07.013330+00:00 [queued]>
[2024-08-28T03:03:08.716+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movies_dag.leer_data manual__2024-08-28T03:03:07.013330+00:00 [queued]>
[2024-08-28T03:03:08.717+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 4
[2024-08-28T03:03:08.731+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): leer_data> on 2024-08-28 03:03:07.013330+00:00
[2024-08-28T03:03:08.739+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=130) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-28T03:03:08.741+0000] {standard_task_runner.py:72} INFO - Started process 132 to run task
[2024-08-28T03:03:08.742+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'movies_dag', 'leer_data', 'manual__2024-08-28T03:03:07.013330+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmps1ersmif']
[2024-08-28T03:03:08.743+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask leer_data
[2024-08-28T03:03:08.783+0000] {task_command.py:467} INFO - Running <TaskInstance: movies_dag.leer_data manual__2024-08-28T03:03:07.013330+00:00 [running]> on host 988f997ce349
[2024-08-28T03:03:08.856+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='pedro' AIRFLOW_CTX_DAG_ID='movies_dag' AIRFLOW_CTX_TASK_ID='leer_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-28T03:03:07.013330+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-28T03:03:07.013330+00:00'
[2024-08-28T03:03:08.857+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-28T03:03:08.869+0000] {logging_mixin.py:190} INFO - None
[2024-08-28T03:03:08.869+0000] {bd_connect.py:26} INFO - Connecting to database...
[2024-08-28T03:03:08.870+0000] {dag_intermediario.py:32} ERROR - ('Connection could not be made due to the following error: \n', ValueError("invalid literal for int() with base 10: 'None'"))
[2024-08-28T03:03:08.870+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-08-28T03:03:08.879+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-28T03:03:08.879+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=movies_dag, task_id=leer_data, run_id=manual__2024-08-28T03:03:07.013330+00:00, execution_date=20240828T030307, start_date=20240828T030308, end_date=20240828T030308
[2024-08-28T03:03:08.916+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-28T03:03:08.931+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-28T03:03:08.933+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
